--@Autor(es):       Alonso Lopez y Marcelino Cisneros
--@Fecha creación:  08/01/2021
--@Descripción:     Creacion de Tablas globales

-- 
-- TABLE: SUCURSAL 
--

CREATE TABLE SUCURSAL
(
    SUCURSAL_ID    NUMBER(10,0)     CONSTRAINT SUCURSAL_PK PRIMARY KEY ,
    CLAVE          VARCHAR2(10)     NOT NULL,
    ES_TALLER      NUMBER(1, 0)     NOT NULL,
    ES_VENTA       NUMBER(1, 0)     NOT NULL,
    NOMBRE         VARCHAR2(40)     NOT NULL,
    LATITUD        FLOAT            NULL,
    LONGITUD       FLOAT            NULL,
    URL            VARCHAR2(200)    NOT NULL
);



-- 
-- TABLE: SUCURSAL_VENTA 
--

CREATE TABLE SUCURSAL_VENTA
(
    SUCURSAL_ID      NUMBER(10,0)    CONSTRAINT SUCURSAL_VENTA_PK PRIMARY KEY,
    HORA_APERTURA    DATE             NOT NULL,
    HORA_CIERRE      DATE             NOT NULL,
    CONSTRAINT SUCURSAL_VENTA_ID_FK FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL(SUCURSAL_ID)
);


-- 
-- TABLE: SUCURSAL_TALLER 
--

CREATE TABLE SUCURSAL_TALLER
(
    SUCURSAL_ID          NUMBER(10,0)   CONSTRAINT SUCURSAL_TALLER_PK PRIMARY KEY,
    DIA_DESCANSO         NUMBER(1,0)    NOT NULL,
    TELEFONO_ATENCION    VARCHAR2(20)   NOT NULL,
    CONSTRAINT SUCURSAL_TALLER_ID_FK FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL(SUCURSAL_ID)
);




-- 
-- TABLE: TIPO_ALMACENAMIENTO 
--

CREATE TABLE TIPO_ALMACENAMIENTO
(
    TIPO_ALMACENAMIENTO_ID    NUMBER(10,0)      CONSTRAINT TIPO_ALMACENAMIENTO_PK PRIMARY KEY,
    CLAVE                     VARCHAR2(40)      NOT NULL,
    DESCRIPCION               VARCHAR2(400)     NOT NULL
);



-- 
-- TABLE: TIPO_MONITOR 
--

CREATE TABLE TIPO_MONITOR
(
    TIPO_MONITOR_ID    NUMBER(10,0)     CONSTRAINT TIPO_MONITOR_PK PRIMARY KEY,
    CLAVE              VARCHAR2(40)     NOT NULL,
    DESCRIPCION        VARCHAR2(400)    NOT NULL
);



-- 
-- TABLE: TIPO_PROCESADOR 
--

CREATE TABLE TIPO_PROCESADOR
(
    TIPO_PROCESADOR_ID    NUMBER(10,0)      CONSTRAINT TIPO_PROCESADOR_PK PRIMARY KEY,
    CLAVE                 VARCHAR2(40)      NOT NULL,
    DESCRIPCION           VARCHAR2(400)     NOT NULL
);



-- 
-- TABLE: TIPO_TARJETA_VIDEO 
--

CREATE TABLE TIPO_TARJETA_VIDEO
(
    TIPO_TARJETA_VIDEO_ID    NUMBER(10,0)   CONSTRAINT TIPO_TARJETA_VIDEO_PK PRIMARY KEY,
    CLAVE                    VARCHAR2(40)   NOT NULL,
    DESCRIPCION              VARCHAR2(400)  NOT NULL
)
;


-- 
-- TABLE: LAPTOP 
--

CREATE TABLE LAPTOP
(
    LAPTOP_ID                 NUMBER(10,0)      CONSTRAINT LAPTOP_PK PRIMARY KEY,
    NUM_SERIE                 VARCHAR2(19)      NOT NULL,
    CANTIDAD_RAM              NUMBER(6,0)       NOT NULL,
    CARACTERISTICAS_EXTRA     VARCHAR2(2000)    NOT NULL,
    FOTO                      BLOB              NOT NULL,
    TIPO_PROCESADOR_ID        NUMBER(10,0)      NOT NULL,
    TIPO_TARJETA_VIDEO_ID     NUMBER(10,0)      NOT NULL,
    TIPO_ALMACENAMIENTO_ID    NUMBER(10,0)      NOT NULL,
    TIPO_MONITOR_ID           NUMBER(10,0)      NOT NULL,
    LAPTOP_REMPLAZO_ID        NUMBER(10,0)      NULL,
    CONSTRAINT LAPTOP_PROCESADOR_ID_FK FOREIGN KEY (TIPO_PROCESADOR_ID)
    REFERENCES TIPO_PROCESADOR(TIPO_PROCESADOR_ID),
    CONSTRAINT LAPTOP_VIDEO_ID_FK FOREIGN KEY (TIPO_TARJETA_VIDEO_ID)
    REFERENCES TIPO_TARJETA_VIDEO(TIPO_TARJETA_VIDEO_ID),
    CONSTRAINT LAPTOP_ALMACENAMIENTO_ID_FK FOREIGN KEY (TIPO_ALMACENAMIENTO_ID)
    REFERENCES TIPO_ALMACENAMIENTO(TIPO_ALMACENAMIENTO_ID),
    CONSTRAINT LAPTOP_MONITOR_ID_FK FOREIGN KEY (TIPO_MONITOR_ID)
    REFERENCES TIPO_MONITOR(TIPO_MONITOR_ID),
    CONSTRAINT LAPTOP_ID_FK FOREIGN KEY (LAPTOP_REMPLAZO_ID)
    REFERENCES LAPTOP(LAPTOP_ID)
);


-- 
-- TABLE: SERVICIO_LAPTOP 
--

CREATE TABLE SERVICIO_LAPTOP(
    NUM_SERVICIO    NUMBER(10,0)     NOT NULL,
    LAPTOP_ID       NUMBER(10,0)     NOT NULL,
    IMPORTE         NUMBER(8,2)      NOT NULL,
    DIAGNOSTICO     VARCHAR2(2000)   NOT NULL,
    FACTURA         BLOB             NULL,
    SUCURSAL_ID     NUMBER(10,0)     NOT NULL,
    CONSTRAINT SERVICIO_LAPTOP_PK PRIMARY KEY (NUM_SERVICIO, LAPTOP_ID),
    CONSTRAINT SUCURSAL_LAPTOP_ID_FK FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_TALLER(SUCURSAL_ID),
    CONSTRAINT SERVICIO_LAPTOP_ID_FK FOREIGN KEY (LAPTOP_ID)
    REFERENCES LAPTOP(LAPTOP_ID)
);



-- 
-- TABLE: STATUS_LAPTOP 
--

CREATE TABLE STATUS_LAPTOP
(
    STATUS_LAPTOP_ID    NUMBER(5,0)     CONSTRAINT STATUS_LAPTOP_PK PRIMARY KEY,
    CLAVE               VARCHAR2(40)    NOT NULL,
    DESCRIPCION         VARCHAR2(400)   NOT NULL
    
);




-- 
-- TABLE: LAPTOP_INVENTARIO 
--

CREATE TABLE LAPTOP_INVENTARIO
(
    LAPTOP_ID           NUMBER(10,0)    CONSTRAINT LAPTOP_INVENTARIO_PK PRIMARY KEY,
    FECHA_STATUS        TIMESTAMP(6)    NOT NULL,
    RFC_CLIENTE         VARCHAR2(13),	NULL,	
    NUM_TARJETA         VARCHAR2(18),   NULL,
    SUCURSAL_ID         NUMBER(10,0)    NOT NULL,
    STATUS_LAPTOP_ID    NUMBER(5,0)     NOT NULL,
    CONSTRAINT LAPTOP_INVENTARIO_ID_FK FOREIGN KEY (LAPTOP_ID)
    REFERENCES LAPTOP(LAPTOP_ID),
    CONSTRAINT INVENTARIO_SUCURSAL_ID_FK FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_VENTA(SUCURSAL_ID),
    CONSTRAINT STATUS_INVENTARIO_ID_FK FOREIGN KEY (STATUS_LAPTOP_ID)
    REFERENCES STATUS_LAPTOP(STATUS_LAPTOP_ID)
);



-- 
-- TABLE: HISTORICO_STATUS_LAPTOP 
--

CREATE TABLE HISTORICO_STATUS_LAPTOP
(
    HISTORICO_STATUS_LAPTOP_ID    NUMBER(10,0)    CONSTRAINT HISTORICO_STATUS_PK PRIMARY KEY ,
    FECHA_STATUS                  TIMESTAMP(6)    NOT NULL,
    STATUS_LAPTOP_ID              NUMBER(5,0)     NOT NULL,
    LAPTOP_ID                     NUMBER(10,0)    NOT NULL,
    CONSTRAINT INVENTARIO_HISTORICO_ID_FK FOREIGN KEY (LAPTOP_ID)
    REFERENCES LAPTOP_INVENTARIO(LAPTOP_ID),
    CONSTRAINT STATUS_HISTORICO_ID_FK FOREIGN KEY (STATUS_LAPTOP_ID)
    REFERENCES STATUS_LAPTOP(STATUS_LAPTOP_ID)
);